ERROR_MESSAGES = {
    "invalid_register_payload": "注册参数不完整或格式错误",
    "password_too_short": "密码长度至少为6位",
    "login_user_id_exists": "登录用户ID已存在",
    "email_exists": "邮箱已被使用",
    "invalid_login_payload": "登录参数不完整或格式错误",
    "invalid_update_profile_payload": "个人资料更新参数不完整或格式错误",
    "invalid_credentials": "登录失败：账号或密码错误",
    "database_url_missing": "数据库连接未配置",
    "db_driver_missing_install_psycopg": "缺少数据库驱动，请安装 psycopg 或 psycopg2",
    "password_hash_format_invalid": "用户密码格式异常",
    "register_failed_psycopg": "注册失败（数据库异常）",
    "register_failed_psycopg2": "注册失败（数据库异常）",
    "login_failed_psycopg": "登录失败（数据库异常）",
    "login_failed_psycopg2": "登录失败（数据库异常）",
    "update_profile_failed_psycopg": "更新资料失败（数据库异常）",
    "update_profile_failed_psycopg2": "更新资料失败（数据库异常）",
    "empty_frame": "上传图片为空",
    "invalid_image": "上传图片无法解析",
    "snapshot_encode_failed": "快照编码失败",
    "snapshot_not_found": "当前无可用快照",
    "invalid_duration_minutes": "房间时长参数不合法",
    "invite_code_generation_failed": "邀请码生成失败",
    "invalid_invite_code_format": "邀请码格式错误，应为12位数字",
    "invite_not_found": "邀请码不存在",
    "invite_not_active": "邀请码已失效",
    "room_not_found": "房间不存在",
    "room_not_active": "房间未处于可加入状态",
    "room_closed": "房间已关闭",
    "not_room_member": "你不是该房间成员",
    "not_room_host": "仅房主可执行该操作",
    "room_member_conflict": "用户已在房间中",
    "room_member_limit_reached": "房间人数已达上限",
    "host_active_room_exists": "你已有进行中的房间，请先结束后再创建新房间",
    "user_not_found": "用户不存在",
    "room_create_failed": "创建房间失败（数据库异常）",
    "room_join_failed": "加入房间失败（数据库异常）",
    "room_leave_failed": "离开房间失败（数据库异常）",
    "room_close_failed": "关闭房间失败（数据库异常）",
    "room_get_failed": "查询房间失败（数据库异常）",
    "room_resume_check_failed": "房间恢复检查失败（数据库异常）",
    "room_study_time_failed": "学习时长统计失败（数据库异常）",
    "room_recommendation_failed": "自习室推荐失败（数据库异常）",
    "invalid_days_range": "统计天数范围不合法",
    "user_stats_failed": "用户学习统计失败（数据库异常）",
    "message_content_empty": "消息内容不能为空",
    "message_too_long": "消息内容超过长度限制",
    "invalid_message_query": "消息查询参数不合法",
    "invalid_read_cursor_payload": "已读游标参数不合法",
    "chat_message_not_found": "消息不存在或不属于当前会话",
    "chat_conversation_failed": "会话查询失败（数据库异常）",
    "chat_send_failed": "发送消息失败（数据库异常）",
    "chat_list_failed": "消息查询失败（数据库异常）",
    "chat_read_cursor_failed": "更新已读游标失败（数据库异常）",
    "internal_server_error": "服务器内部错误",
    "http_error": "请求处理失败",
}


def get_error_message(code: str) -> str:
    return ERROR_MESSAGES.get(code, "请求失败")
